config/routes.rb
Rails.application.routes.draw do
  devise_for :agents

  root 'home#index'

  get 'index' => 'home#index'
  get 'contact_us' => 'home#contact_us'
  get 'policies' => 'home#policies'
  get 'signup' => 'home#signup'

  resources :applicants do
    collection do
      get 'import'
      post 'csv_import'
    end

    member do
      get 'pdf_report', defaults: { format: 'pdf' }
      get 'send_form', 'capture_signature', 'signature_confirmation', 'get_signed_form', 'get_envelope_status'
    end
  end

end

app/models/applicant.rb
require 'csv'

class Applicant < ActiveRecord::Base
  attr_accessor :ss_number1, :ss_number2, :ss_number3

  belongs_to :agent
  has_one :applicant_signature

  validates_presence_of :email
  validates_uniqueness_of :email

  PLAN_LIST = { "A" => "A $139/month", "B" => "B $199/month", "C" => "C $139/month", "C+" => "C+ Additional $29 a month" }

  def self.csv_import(file, agent)
    CSV.foreach(file.path, headers: true) do |row|
      applicant_hash = row.to_hash
      email = applicant_hash["Email"]

      applicant = Applicant.find_by_email(email) || agent.applicants.new(email: email)
      applicant.name = applicant_hash["Name"]
      applicant.dob = applicant_hash["DOB"]
      applicant.sex = applicant_hash["Sex"]
      applicant.state = applicant_hash["State"]
      applicant.country = applicant_hash["Country"]
      applicant.facility_of_residents = applicant_hash["Facility of Residents"]
      applicant.medicaid_number = applicant_hash["Medicaid Number"]
      applicant.medicaid_case_worker = applicant_hash["Medicaid Case Worker"]
      applicant.ss_number = applicant_hash["SS Number"]
      applicant.address = applicant_hash["Address"]
      applicant.phone = applicant_hash["Phone"]
      applicant.save
    end
  end

  def docusign_client
    @docusign_client ||= DocusignRest::Client.new
  end

  def envelope_url(return_url, default_url)
    response = docusign_client.get_recipient_view(
                                     client_id: id,
                                     envelope_id: envelope_id,
                                     name: "Test Host", #host name for in person signer
                                     email: "biappstestemail@gmail.com",  #host email for in person signer
                                     return_url: return_url
                                     )
    if response["url"].present?
      return response["url"]
    else
      return default_url
    end
  end

  def get_signed_form
    response = docusign_client.get_document_from_envelope(
                                    envelope_id: envelope_id,
                                    document_id: 1,
                                    local_save_path: "#{Rails.root.join('docusign_docs/' + envelope_id + '.pdf')}"
                                    )

  end

  def get_envelope_status
    response = docusign_client.get_envelope_status(envelope_id: envelope_id)
    self.envelope_status = response["status"]
    self.save
  end
end

app/controllers/applicants_controller.rb
class ApplicantsController < ApplicationController
  before_action :authenticate_agent!, except: [:new, :create, :send_form]

  def index
    if current_agent.admin?
      @applicants = Applicant.all
    else
      @applicants = current_agent.applicants
    end
  end

  def new
    @applicant = Applicant.new
  end

  def create
    agent = current_agent || Agent.find_or_create_agent("info@businessinsighter.com")

    ss_params = applicant_params.slice(:ss_number, :ss_number1, :ss_number2, :ss_number3)
    applicant_attr = applicant_params.slice!(:ss_number, :ss_number1, :ss_number2, :ss_number3)

    @applicant = agent.applicants.new(applicant_params)
    @applicant.ss_number = ss_params.values.join("-")

    if @applicant.save
      if params[:unlisted_applicant] == "true"
        flash[:notice] = "Thank you for submitting form..."
        redirect_to applicants_path
      else
        redirect_to send_form_applicant_path(@applicant)
      end
    else
      flash[:error] = @applicant.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit
    @applicant = Applicant.find_by_id(params[:id])
    @signature = @applicant.applicant_signature || @applicant.build_applicant_signature
  end

  def capture_signature
    @applicant = Applicant.find_by_id(params[:id])

    unless @applicant.envelope_id.present?
      client = DocusignRest::Client.new
      response = client.create_envelope_from_document(
        email: {
          subject: "Dentsured form",
          body: "Please go through the document and sign."
        },
        in_person_signers: [{
          embedded: true,
          hostEmail: "biappstestemail@gmail.com",
          hostName: "Test Host",
          recipientId: @applicant.id,
          signerName: @applicant.name,
          signerEmail: @applicant.email,
          clientUserId: @applicant.id
        }],
        files: [
          {path: "#{Rails.root}/public/form.pdf", name: 'form.pdf'}
        ],
        status: 'sent')
      @applicant.envelope_id = response["envelopeId"]
      @applicant.envelope_status = response["status"]
      @applicant.save

    end
  end

  def update
    applicant = Applicant.find_by_id(params[:id])

    ss_params = applicant_params.slice(:ss_number, :ss_number1, :ss_number2, :ss_number3)
    applicant.attributes = applicant_params.slice!(:ss_number, :ss_number1, :ss_number2, :ss_number3)
    applicant.ss_number = ss_params.values.join("-")
    applicant.save

    redirect_to capture_signature_applicant_path(applicant)
  end

  def show
    @applicant = Applicant.find_by_id(params[:id])
  end

  def delete
  end

  def signature_confirmation
    @applicant = Applicant.find_by_id(params[:id])

    client = DocusignRest::Client.new
    response = client.get_envelope_recipients(
                                              envelope_id: @applicant.envelope_id,
                                              include_tabs: true,
                                              include_extended: true
                                              )
    @applicant.envelope_status = response["inPersonSigners"][0]["status"]
    @applicant.save

    render layout: false
  end

  def csv_import
    Applicant.csv_import(params[:file], current_agent)
    flash[:success] = "CSV imported successfully."
    redirect_to applicants_path
  end

  def send_form
    applicant = Applicant.find_by_id(params[:id])

    client = DocusignRest::Client.new
    document_envelope_response = client.create_envelope_from_document(
      email: {
       subject: "Dentsured form",
       body: "Please go through the document and sign."
      },
    signers: [
    {
      name: applicant.name,
      email: applicant.email, #'biappstestemail@gmail.com'
      role_name: 'Applicant'
    }
  ],
  files: [
    {path: "#{Rails.root}/public/form.pdf", name: 'form.pdf'}
  ],
  status: 'sent')
    applicant.envelope_id = document_envelope_response["envelopeId"]
    applicant.envelope_status = document_envelope_response["status"]
    applicant.save
    flash[:notice] = "Thank you for submitting form..."

    if current_agent
      redirect_to applicants_path
    else
      redirect_to policies_path
    end
  end

  def get_signed_form
    @applicant = Applicant.find_by_id(params[:id])

    if @applicant.envelope_id.present?
      @applicant.get_signed_form
      @filename = "docusign_docs/" + "#{@applicant.envelope_id}.pdf"
      @file = "#{Rails.root.join(@filename)}"
      Aws.config.update(
                        credentials: Aws::Credentials.new(Figaro.env.AWS_ACCESS_KEY_ID, Figaro.env.AWS_SECRET_ACCESS_KEY),
                        region: 'us-west-2'
                        )
      s3_bucket = Aws::S3::Bucket.new(name: "dentsures",region: "us-west-2")
      obj = s3_bucket.object(@filename)
      obj.upload_file(@filename, acl: 'public-read')
      @applicant.signed_form_path = obj.public_url
      @applicant.save
    end
  end

  def get_envelope_status
    @applicant = Applicant.find_by_id(params[:id])
    @applicant.get_envelope_status
  end

  private

  def applicant_params
    params.require(:applicant).permit(:name, :middle_initial, :last_name, :dob, :sex, :state, :city, :zip, :country, :facility_of_residents, :medicaid_number, :medicaid_case_worker, :ss_number, :ss_number1, :ss_number2, :ss_number3, :address, :email, :phone, :communication_preference, :plan, :primary_dentist_name, :primary_dentist_telephone, applicant_signature: [:data])
  end
end

app/helpers/applicants_helper.rb
module ApplicantsHelper
  def applicant_name_link(applicant)
    if applicant.envelope_status == "completed"
      applicant_path(applicant)
    else
      edit_applicant_path(applicant)
    end
  end
end

app/views/applicants/_form.html.erb
  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control", required: true %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :email, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.email_field :email, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :phone, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :phone, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :dob, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :dob, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :sex, "Gender", class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.select :sex, [["Male", "Male"], ["Female", "Female"]], { prompt: "Please Select" }, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :state, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :state, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :country, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :country, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :facility_of_residents, "Facility of Residence", class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :facility_of_residents, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :medicaid_number, "Medicaid Number", class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :medicaid_number, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :medicaid_case_worker, "Name of Medicaid Representative", class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :medicaid_case_worker, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :ss_number, "Social Security Number", class: "col-sm-2 control-label" %>
    <div class="col-sm-10 ss-number">
      <%= f.text_field :ss_number1, class: "form-control ss-number1" %> - <%= f.text_field :ss_number2, class: "form-control ss-number2" %> - <%= f.text_field :ss_number3, class: "form-control ss-number3" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :address, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :address, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :communication_preference, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.select :communication_preference, [["Email", "email"], ["Facility", "facility"], ["Mail", "mail"]],
          { prompt: "Please Select" }, class: "form-control" %>
    </div>
  </div>

  <p class="plan-description">Company is hereby authorized to enroll the above applicant in Dentsured Plan A B C C+ (circle requested Plan) and to bill the corresponding Premium as listed below on a monthly basis directly to the patient trust account or to authorized agent, and to adjust the patient pay liability accordingly.</p>
  
  <div class="form-group">
    <%= f.label :plan, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.select :plan, Applicant::PLAN_LIST.invert.to_a,
          { prompt: "Please Select" }, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :primary_dentist_name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :primary_dentist_name, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :primary_dentist_telephone, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :primary_dentist_telephone, class: "form-control" %>
    </div>
  </div>

app/views/applicants/capture_signature.html.erb
<iframe src="<%= @applicant.envelope_url(signature_confirmation_applicant_url(@applicant, host: Figaro.env.BASE_URL), edit_applicant_url(@applicant, host: Figaro.env.BASE_URL)) %>", frameborder=0, class="docusign-iframe"></iframe>

app/views/applicants/edit.html.erb
<div class="row">
  <div class="col-sm-12">
    <h2>Signup <%= @applicant.name %></h2>
  </div>
</div>

<%= form_for @applicant, html: { class: "form-horizontal edit-applicant" } do |f| %>

  <%= render 'form', f: f %>
  
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= link_to "View Signed Form", get_signed_form_applicant_path(@applicant), class: "btn btn-primary" %>
      <%= f.submit "Applicant Signature", class: "btn btn-primary" %>
      <%= link_to "Cancel", :back, class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/applicants/get_envelope_status.html.erb
<h2><%= @applicant.name %>'s Docusign Status: <%= @applicant.envelope_status %></h2>

app/views/applicants/get_signed_form.html.erb
<% if @file %>
  <div class="docusign-signed-pdf">
    <object data="<%= @applicant.signed_form_path %>" type="application/pdf" width="1000" height="600">
       alt : <a href="<%= @applicant.signed_form_path %>"><%= @applicant.name %></a>
    </object>
  </div>
<% else %>
  <p> There is no signed form available yet. Please first complete the signing procedure.</p>
<% end %>

app/views/applicants/import.html.erb
<div class="row">
  <div class="col-sm-12">
    <h2>Applicants CSV Import</h2>
  </div>
</div>

<%= form_tag csv_import_applicants_path, multipart: true, class: "form-inline applicants-csv-import" do %>
  <div class="form-group">
    <%= file_field_tag :file, class: "form-control", required: true %>
  </div>
  <%= submit_tag "Import CSV", class: "btn btn-primary" %>
<% end %>

app/views/applicants/index.html.erb
<div class="row">
  <div class="col-sm-12">
    <h2>Applicants</h2>
  </div>
</div>

<table class="table table-striped applicants">
  <thead>
    <tr>
      <td>Name</td>
      <td>Email</td>
      <td>DoB</td>
      <td>State</td>
      <td>Medicaid Number</td>
      <td>SS Number</td>
    </tr>
  </thead>
  <tbody>
    <% @applicants.each do |applicant| %>
      <tr>
        <td><%= link_to applicant.name, edit_applicant_path(applicant) %></td>
        <td><%= applicant.email %></td>
        <td><%= applicant.dob %></td>
        <td><%= applicant.state %></td>
        <td><%= applicant.medicaid_number %></td>
        <td><%= applicant.ss_number %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "Sign up unlisted Patient", new_applicant_path(unlisted_applicant: true), class: "btn btn-primary" %>

<script type="text/javascript">
  $('.applicants').DataTable();
</script>

app/views/applicants/new.html.erb
<div class="row">
  <div class="col-sm-12">
    <h2>Please fill out the following information to sign up for Dentsured. The policy
does not take effect immediately, until you are contacted by one of our sales representatives to
complete the contract</h2>
  </div>
</div>

<%= form_for @applicant, html: { class: "form-horizontal" } do |f| %>

  <%= render 'form', f: f %>
  <%= hidden_field_tag :unlisted_applicant, params[:unlisted_applicant] %>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit "Submit", class: "btn btn-primary" %>
      <%= f.submit "Cancel", type: "reset", class: "btn btn-primary", "data-confirm" => "Are you sure?" %>
    </div>
  </div>
<% end %>

app/views/applicants/pdf_report.pdf.erb
<!doctype html>
<html>
  <head>
    <meta charset='utf-8' />
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" -%>
  </head>
  <body onload='number_pages'>
    <div class="container">
        <dl class="dl-horizontal">
          <dt>Name</dt>
          <dd><%= @applicant.name %></dd>
  
          <dt>Email</dt>
          <dd><%= @applicant.email %></dd>

          <dt>Date of Birth</dt>
          <dd><%= @applicant.dob %></dd>

          <dt>Sex</dt>
          <dd><%= @applicant.sex %></dd>

          <dt>State</dt>
          <dd><%= @applicant.state %></dd>

          <dt>Country</dt>
          <dd><%= @applicant.country %></dd>

          <dt>Facility of Residents</dt>
          <dd><%= @applicant.facility_of_residents %></dd>

          <dt>Medicaid Number</dt>
          <dd><%= @applicant.medicaid_number %></dd>

          <dt>Medicaid Case Worker</dt>
          <dd><%= @applicant.medicaid_case_worker %></dd>

          <dt>SS Number</dt>
          <dd><%= @applicant.ss_number %></dd>

          <dt>Address</dt>
          <dd><%= @applicant.address %></dd>

          <dt>Phone</dt>
          <dd><%= @applicant.phone %></dd>

          <dt>Authorized Agent</dt>
          <dd><%= @applicant.agent.name %></dd>
        </dl>
       
        <% if @applicant.applicant_signature.try(:image).present? %>
          <div class="pull-right">
            <%= wicked_pdf_image_tag (@applicant.applicant_signature.image.url) %>
          </div>
        <% end %>     
    </div>
  </body>
</html>

app/views/applicants/show.html.erb
<div class="row">
  <div class="col-sm-12">
    <h2>Applicant Profile</h2>
  </div>
</div>

<dl class="dl-horizontal">
  <dt>Name</dt>
  <dd><%= @applicant.name %></dd>
  
  <dt>Email</dt>
  <dd><%= @applicant.email %></dd>

  <dt>Date of Birth</dt>
  <dd><%= @applicant.dob %></dd>

  <dt>Sex</dt>
  <dd><%= @applicant.sex %></dd>

  <dt>State</dt>
  <dd><%= @applicant.state %></dd>

  <dt>Country</dt>
  <dd><%= @applicant.country %></dd>

  <dt>Facility of Residents</dt>
  <dd><%= @applicant.facility_of_residents %></dd>

  <dt>Medicaid Number</dt>
  <dd><%= @applicant.medicaid_number %></dd>

  <dt>Medicaid Case Worker</dt>
  <dd><%= @applicant.medicaid_case_worker %></dd>

  <dt>SS Number</dt>
  <dd><%= @applicant.ss_number %></dd>

  <dt>Address</dt>
  <dd><%= @applicant.address %></dd>

  <dt>Phone</dt>
  <dd><%= @applicant.phone %></dd>

  <dt>Authorized Agent</dt>
  <dd><%= @applicant.agent.name %></dd>
  
  <% if @applicant.applicant_signature.try(:image).present? %>
    <dt>Signature</dt>
    <dd><%= image_tag @applicant.applicant_signature.image.url %></dd>
  <% end %>
</dl>

<div class="row">
  <%= link_to "PDF Report", pdf_report_applicant_path(@applicant), class: "btn btn-primary" %>
  <%= link_to "Applicant's Signature", edit_applicant_path(@applicant), class: "btn btn-primary" %>
  <%= link_to "Back", applicants_path, class: "btn btn-primary" %>
</div>

app/views/applicants/signature_confirmation.html.erb
<div>
  Applicant Signature Capture Process is Completed.
</div>