config/routes.rb
Rails.application.routes.draw do
  devise_for :agents

  root 'home#index'

  get 'index' => 'home#index'
  get 'contact_us' => 'home#contact_us'
  get 'policies' => 'home#policies'
  get 'signup' => 'home#signup'

  resources :applicants do
    collection do
      get 'import'
      post 'csv_import'
    end

    member do
      get 'pdf_report', defaults: { format: 'pdf' }
      get 'send_form', 'capture_signature', 'signature_confirmation', 'get_signed_form', 'get_envelope_status'
    end
  end

end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-left">
        <li>
          <%= link_to image_tag('Logo.png', size: "80x60"), root_path %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">

        <% if agent_signed_in? %>
        <% if current_agent.admin? %>
        <li><%= link_to "Import", import_applicants_path %></li>
        <% end %>
        <li><%= link_to "Applicants", applicants_path %></li>
        <li><%= link_to "Logout", destroy_agent_session_path, method: :delete %></li> <% else %>
        <li><%= link_to "Login", new_agent_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dentsured</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/navigation' %>

    <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>

    <div class="container">
      <%= yield %>
    </div>

    <p></p><p></p><p></p>
    <footer class="footer">
      <small>
        <p>Copyright &copy; Dentsures  |   Contact information: <a href="mailto:info@dentured.com">
          info@dentured.com</a>   |   1 844 877 8733</p>
      </small>
<!--       </center> -->
    </footer>
  </body>
</html>